[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap_program = "HE1mqZFn3DAuNbj1YL3MfRqEWeZ8uUMWBgcAV6J9PzJb"

[programs.devnet]
swap_program = "HE1mqZFn3DAuNbj1YL3MfRqEWeZ8uUMWBgcAV6J9PzJb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/local-id.json"

# [provider]
# cluster = "Devnet"
# wallet = "~/.config/solana/devnet-id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
